### ISSUE TITLE
quickbooks login doesn't work, page html has changed

### ISSUE THREAD

**Issue by frrmack** [datascopeanalytics/a-model#24]
sync with quickbooks fails hencewithforthsince.

**Comment by frrmack** [comment]
I fixed this. Login happens, it downloads the excel files successfully. However, there is another (new) issue. Upload to google drive fails:

```
(a-model)TheProbtyEngine:a-model irmak$ bin/sync_quickbooks_gdrive.py 
/Users/irmak/Projects/a-model/.data/revenue_projections.xlsx
Traceback (most recent call last):
  File "bin/sync_quickbooks_gdrive.py", line 18, in <module>
    reports.sync_local_cache_with_gdrive()
  File "/Users/irmak/Projects/a-model/a_model/reports/__init__.py", line 26, in sync_local_cache_with_gdrive
    ARAging().upload_to_gdrive()
  File "/Users/irmak/Projects/a-model/a_model/reports/base.py", line 168, in upload_to_gdrive
    excel_worksheet = self.open_worksheet()
  File "/Users/irmak/Projects/a-model/a_model/reports/base.py", line 192, in open_worksheet
    workbook = openpyxl.load_workbook(self.filename)
  File "/Users/irmak/.virtualenvs/a-model/lib/python2.7/site-packages/openpyxl/reader/excel.py", line 202, in load_workbook
    parsed_styles = read_style_table(archive)
  File "/Users/irmak/.virtualenvs/a-model/lib/python2.7/site-packages/openpyxl/reader/style.py", line 181, in read_style_table
    p.parse()
  File "/Users/irmak/.virtualenvs/a-model/lib/python2.7/site-packages/openpyxl/reader/style.py", line 53, in parse
    self.parse_named_styles()
  File "/Users/irmak/.virtualenvs/a-model/lib/python2.7/site-packages/openpyxl/reader/style.py", line 109, in parse_named_styles
    names = self._parse_style_names()
  File "/Users/irmak/.virtualenvs/a-model/lib/python2.7/site-packages/openpyxl/reader/style.py", line 128, in _parse_style_names
    for _name in node:
TypeError: 'NoneType' object is not iterable
```

Although this is a new issue, I'll keep it here, since it's still a failure of the initial `sync_quickbooks_gdrive.py` run.

**Comment by frrmack** [comment]
It downloads the four reports alright. Then, when it's trying to read them, it starts with `ar_aging.xlsx` and fails with the error above. When I open that file in excel, it seems fine, looks good to me.

**Comment by frrmack** [comment]
Probably needs a deeper down look but I don't have the time at the moment. I will do a pull request for my fix to the login part, and will keep this issue open.

**Comment by frrmack** [comment]
Interesting. If I open the file in Excel and save it (without any changes), then openpyxl can read the file without any issues. I wonder if this is a DOS / OSX file format issue.

**Comment by frrmack** [comment]
But even if I open and save all excel files to make sure pyopenxl can read them, new errors come up during parsing, like this:

```
(a-model)TheProbtyEngine:a-model irmak$ bin/simulate_cash_in_bank.py 
reading worksheet from /Users/irmak/Projects/a-model/.data/balance_sheet.xlsx
/Users/irmak/.virtualenvs/a-model/lib/python2.7/site-packages/openpyxl/reader/worksheet.py:320: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/Users/irmak/.virtualenvs/a-model/lib/python2.7/site-packages/openpyxl/worksheet/worksheet.py:374: UserWarning: Call to deprecated function or class get_highest_column (Use the max_column propery.).
  def get_highest_column(self):
reading worksheet from /Users/irmak/Projects/a-model/.data/unpaid_invoices.xlsx
Traceback (most recent call last):
  File "bin/simulate_cash_in_bank.py", line 35, in <module>
    verbose=args.verbose,
  File "/Users/irmak/Projects/a-model/a_model/datascope.py", line 246, in simulate_monthly_cash
    self._simulate_single_universe_monthly_cash(universe, n_months)
  File "/Users/irmak/Projects/a-model/a_model/datascope.py", line 225, in _simulate_single_universe_monthly_cash
    revenues = self.simulate_revenues(universe, n_months)
  File "/Users/irmak/Projects/a-model/a_model/decorators.py", line 51, in wrapped_method
    result = method(*args, **kwargs)
  File "/Users/irmak/Projects/a-model/a_model/datascope.py", line 164, in simulate_revenues
    for date, balance in self.unpaid_invoices:
  File "/Users/irmak/Projects/a-model/a_model/reports/unpaid_invoices.py", line 29, in __iter__
    projected_payments = self.get_projected_payments()
  File "/Users/irmak/Projects/a-model/a_model/reports/unpaid_invoices.py", line 24, in get_projected_payments
    self.get_float_from_cell(balance_cell),
  File "/Users/irmak/Projects/a-model/a_model/reports/base.py", line 247, in get_float_from_cell
    return float(float_cell.value.strip('='))
AttributeError: 'long' object has no attribute 'strip'
```

As you can see, the code's expectations of what to find in a specific cell and what there is in reality do not match. I wonder if quickbooks changed the format of the excel files since the last time this code was run. That would explain this.

**Comment by deanmalmgren** [comment]
@frrmack I think the lingering issue might be a version problem. What version of openpyxl do you have? 

`python -c 'import openpyxl; print openpyxl.__version__'`

I have version 2.2.5. 

I think the ultimate solution to this is to move to using CSVs. We're currently doing [some kinda janky shit](https://github.com/datascopeanalytics/a-model/blob/master/a_model/reports/base.py#L241-L247) to read in the excel values and we're not currently catching the case where `long` values are read from an excel spreadsheet (which will fix the latest traceback that you posted). This jankiness comes from (i) quickbooks storing every value in the spreadsheet as a formula and (ii) openpyxl being [unable to compute the resulting value of formulas in excel spreadsheets without connecting to excel bindings](http://stackoverflow.com/questions/23350581/openpyxl-1-8-5-reading-the-result-of-a-formula-typed-in-a-cell-using-openpyxl). This is a little silly, particularly for our use case. I think it should be simple enough to switch to CSV format and reconfigure the `reports` to reading a CSV instead of an excel spreadsheet.

I'll create a new issue for the CSV switch and close out this issue momentarily with a `long` patch. 

Thanks for bringing this up and for documenting the traceback!
