### ISSUE TITLE
error running bin/sync_quickbooks_gdrive.py revenue_projections 

### ISSUE THREAD

**Issue by stringertheory** [datascopeanalytics/a-model#32]
```
Traceback (most recent call last):
  File "bin/sync_quickbooks_gdrive.py", line 22, in <module>
    reports.cache_quickbooks_locally(username, password, reports=args.reports)
  File "/Users/stringer/Projects/a-model/a_model/reports/__init__.py", line 86, in cache_quickbooks_locally
    report_cls().download_from_gdrive()
  File "/Users/stringer/Projects/a-model/a_model/reports/base.py", line 220, in download_from_gdrive
    output.write(response.read())
AttributeError: 'str' object has no attribute 'read'
```

**Comment by stringertheory** [comment]
I think maybe @deanmalmgren has a wittle :bug:

**Comment by deanmalmgren** [comment]
Aaaaaaaaaaaaaaaaaaahhhhhhhhhhhhhhhhhhhhjhhhh

**Comment by deanmalmgren** [comment]
I can't reproduce this. Happy to pair on it for a few minutes to figure out whats going on.
